---
swagger: "2.0"
info:
  description: "Api de teste para o swagger"
  version: "1.0.0"
  title: "Bytebank Api"
  termsOfService: "http://localhost:8080/bytebank-api/v1"
  contact:
    name: "Suporte Bytebank"
    url: "http://localhost:8080/bytebank-api/v1/suporte"
    email: "suporte@bytebankapi.com"
host: "localhost:8080"
basePath: "/bytebank-api/v1"
tags:
- name: "Cliente"
- name: "Conta"
- name: "Extrato"
- name: "Transacao"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
security:
- BasicAuth: []
paths:
  /cliente:
    post:
      tags:
      - "Cliente"
      summary: "Cadastra Cliente"
      description: "Cadastra um novo cliente"
      operationId: "cadastraCliente"
      parameters:
      - in: "body"
        name: "cliente_"
        required: false
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        "201":
          description: "Cadastro efetuado com sucesso"
          schema:
            $ref: "#/definitions/Cliente"
        "400":
          description: "Requisição inválida"
        "500":
          description: "Erro interno no servidor"
      x-swagger-router-controller: "Cliente"
  /conta/{agencia}/{numero}/{digito}/saldo:
    get:
      tags:
      - "Conta"
      summary: "Consulta Saldo"
      description: "Consulta saldo da conta do cliente"
      operationId: "consultaSaldo"
      parameters:
      - name: "agencia"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "numero"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "digito"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "Consulta ao saldo efetuado com sucesso"
          schema:
            type: "number"
            format: "double"
        "400":
          description: "Requisição inválida"
        "401":
          description: "Requisição não autorizada"
        "500":
          description: "Erro no servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Conta"
  /transacao:
    post:
      tags:
      - "Transacao"
      summary: "Cadastra transação na Conta"
      description: "Cadastra uma transação de débito ou depósito na conta."
      operationId: "cadastraTransacao"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "transacao"
        required: true
        schema:
          $ref: "#/definitions/Transacao"
      - name: "tipo"
        in: "query"
        required: true
        type: "string"
        enum:
        - "debito"
        - "deposito"
      responses:
        "201":
          description: "Cadastro de transação efetuado com sucesso"
          schema:
            $ref: "#/definitions/Transacao"
        "400":
          description: "Requisição inválida"
        "401":
          description: "Requisição não autorizada"
        "500":
          description: "Erro no servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Transacao"
  /extrato/{agencia}/{numero}/{digito}:
    get:
      tags:
      - "Extrato"
      summary: "Consulta extrato"
      description: "Consulta o extrato da conta do cliente."
      operationId: "consultaExtrato"
      parameters:
      - name: "agencia"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "numero"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "digito"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "Consulta ao extrato efetuado com sucesso"
          schema:
            $ref: "#/definitions/Extrato"
        "400":
          description: "Requisição inválida"
        "401":
          description: "Requisição não autorizada"
        "500":
          description: "Erro no servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Extrato"
  /transacao/{codigo}:
    put:
      tags:
      - "Transacao"
      summary: "Altera o valor da Transacao"
      description: "Altera o valor da Transacao na conta existente do cliente."
      operationId: "alteraTransacao"
      parameters:
      - name: "codigo"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "valor"
        in: "query"
        required: true
        type: "number"
        format: "double"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "204":
          description: "Alteração do valor efetuado com sucesso"
        "400":
          description: "Requisição inválida"
        "401":
          description: "Requisição não autorizada"
        "500":
          description: "Erro no servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Transacao"
    delete:
      tags:
      - "Transacao"
      summary: "Deleta uma transacao"
      description: "Deleta uma transacao indevida por um cliente."
      operationId: "deletaTransacao"
      parameters:
      - name: "codigo"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "204":
          description: "Transação excluída com sucesso"
        "400":
          description: "Requisição inválida"
        "401":
          description: "Requisição não autorizada"
        "500":
          description: "Erro no servidor"
      security:
      - BasicAuth: []
      x-swagger-router-controller: "Transacao"
securityDefinitions:
  BasicAuth:
    type: "basic"
definitions:
  Cliente:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      titular:
        type: "string"
        example: "Janete Silva"
      cpf:
        type: "string"
        example: "555.555.555-55"
        minLength: 11
        maxLength: 11
      senha:
        type: "string"
        format: "password"
        example: "senha123"
      conta:
        type: "array"
        items:
          $ref: "#/definitions/Conta"
    example:
      senha: "senha123"
      cpf: "555.555.555-55"
      conta:
      - transacoes:
        - tipo: "debito"
          data: "2000-01-23T04:56:07.000+00:00"
          valor: 6.02745618307040320615897144307382404804229736328125
          id: 0
        - tipo: "debito"
          data: "2000-01-23T04:56:07.000+00:00"
          valor: 6.02745618307040320615897144307382404804229736328125
          id: 0
        numero: 784563
        saldo: 101.340000000000003410605131648480892181396484375
        agencia: 975
        digito: 7
      - transacoes:
        - tipo: "debito"
          data: "2000-01-23T04:56:07.000+00:00"
          valor: 6.02745618307040320615897144307382404804229736328125
          id: 0
        - tipo: "debito"
          data: "2000-01-23T04:56:07.000+00:00"
          valor: 6.02745618307040320615897144307382404804229736328125
          id: 0
        numero: 784563
        saldo: 101.340000000000003410605131648480892181396484375
        agencia: 975
        digito: 7
      id: 1
      titular: "Janete Silva"
  Conta:
    type: "object"
    properties:
      agencia:
        type: "integer"
        format: "int32"
        example: 975
      numero:
        type: "integer"
        format: "int64"
        example: 784563
      digito:
        type: "integer"
        format: "int32"
        example: 7
      saldo:
        type: "number"
        format: "double"
        example: 101.340000000000003410605131648480892181396484375
      cliente:
        $ref: "#/definitions/Cliente"
      transacoes:
        type: "array"
        items:
          $ref: "#/definitions/Transacao"
    example:
      transacoes:
      - tipo: "debito"
        data: "2000-01-23T04:56:07.000+00:00"
        valor: 6.02745618307040320615897144307382404804229736328125
        id: 0
      - tipo: "debito"
        data: "2000-01-23T04:56:07.000+00:00"
        valor: 6.02745618307040320615897144307382404804229736328125
        id: 0
      numero: 784563
      saldo: 101.340000000000003410605131648480892181396484375
      agencia: 975
      digito: 7
  Transacao:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      tipo:
        type: "string"
        enum:
        - "debito"
        - "deposito"
      valor:
        type: "number"
        format: "double"
      data:
        type: "string"
        format: "date-time"
      conta:
        $ref: "#/definitions/Conta"
    example:
      tipo: "debito"
      data: "2000-01-23T04:56:07.000+00:00"
      valor: 6.02745618307040320615897144307382404804229736328125
      id: 0
  Extrato:
    type: "object"
    properties:
      transacoes:
        type: "array"
        items:
          $ref: "#/definitions/Transacao"
    example:
      transacoes:
      - tipo: "debito"
        data: "2000-01-23T04:56:07.000+00:00"
        valor: 6.02745618307040320615897144307382404804229736328125
        id: 0
      - tipo: "debito"
        data: "2000-01-23T04:56:07.000+00:00"
        valor: 6.02745618307040320615897144307382404804229736328125
        id: 0
